version: 2
updates:
  # GitHub Actions dependencies in workflows only
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels: ["dependencies","github-actions"]

  # Docker dependencies (base images)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels: ["dependencies","docker"]
    # don't upgrade major versions of eclipse-temurin (Java) automatically
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]