name: 'HL7 FHIR IG Publisher'
description: 'Run HL7 FHIR Implementation Guide Publisher with SUSHI and optional FHIR Package Tool support'
author: 'Gefyra'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  variant:
    description: 'Version to use: "standard" (default) or "with-snapshot-support"'
    required: false
    default: 'standard'
  command:
    description: 'Command to run (igpublisher, sushi, fhir-pkg-tool, or custom)'
    required: false
    default: 'igpublisher'
  args:
    description: 'Arguments to pass to the command'
    required: false
    default: '-ig ig.ini'
  working-directory:
    description: 'Working directory to run the command in'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Run with standard variant
      if: inputs.variant == 'standard'
      uses: docker://ghcr.io/gefyra/ig-publisher:latest
      with:
        args: ${{ inputs.command }} ${{ inputs.args }}
      env:
        WORKING_DIR: ${{ inputs.working-directory }}
        
    - name: Run with snapshot support variant
      if: inputs.variant == 'with-snapshot-support'
      uses: docker://ghcr.io/gefyra/ig-publisher-with-snapshot-support:latest
      with:
        args: ${{ inputs.command }} ${{ inputs.args }}
      env:
        WORKING_DIR: ${{ inputs.working-directory }}